### ISSUE TITLE
Export copies of Dataverse datasets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/researchdata#1]
This epic focuses on retrieving copies of the existing UNC Emory Dataverse deposits, and storing them in a secure, non-public backup location.

- [x] Identify Emory Dataverse datasets to retrieve (and method for how to identify them) 
- [x] Identify key digital object components to export (files, metadata)
- [x] Review Dataverse API
- [x] Generate one or more API keys for use by Scrum team
- [x] Ensure Scrum team can access the UNC Dataverse via API
