### ISSUE TITLE
Identify technology support platforms for research data preservation

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/researchdata#3]
This epic focuses on identifying and documenting a small set of feasible technology support scenarios.

Draft document: Technology Support Scenarios

Tasks:

- [x] Develop draft document
- [x] Identify questions to clarify
- [ ] Review and refine final scenarios
